name: Build and Deploy Franklin.jl site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.11'
        
    - name: Cache Julia packages
      uses: actions/cache@v3
      with:
        path: ~/.julia
        key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-
        
    - name: Install dependencies
      run: |
        julia --project=. -e 'using Pkg; Pkg.instantiate()'
        julia --project=. -e 'using Pkg; Pkg.add("Franklin")'
      
    - name: Build site
      run: julia --project=. -e 'using Franklin; optimize()'
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./__site
        cname: # Add your custom domain here if you have one